services:
  products.api:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    environment:
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: "291103"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_ENVIRONMENT: "Staging"

    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}/.aspnet/https:/https/
